### ISSUE TITLE
version 0.1.18 Highlight js error

### ISSUE THREAD

**Issue by YannickFuereder** [aidanaden/solid-highlight#86]
I'm getting this error in my browser console in dev mode 

"SyntaxError: ambiguous import: HighlightJS"

Using: Solid Start Beta 2

**Comment by aidanaden** [comment]
hi! sorry for the late response - could u send me a reproduction of your error? (github repo, codesandbox, etc)

**Comment by aidanaden** [comment]
Issue should be fixed, current solid start beta 2 example runs via ssr without issue - https://solid-highlight.pages.dev/
